name: Deploy to Maven Central

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  deploy:
    if: github.head_ref == 'develop' || startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
        
      - name: Determine version from branch
        id: version
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Source branch: $BRANCH_NAME"
          
          # Set version based on branch name
          if [[ "$BRANCH_NAME" =~ ^release/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "Release branch detected, version: $VERSION"
          elif [[ "$BRANCH_NAME" == "main" ]]; then
            VERSION="1.2.1"
            echo "Main branch detected, using base version: $VERSION"
          else
            SANITIZED_BRANCH=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9]/-/g')
            VERSION="1.2.1-${SANITIZED_BRANCH}-SNAPSHOT"
            echo "Feature branch detected, version: $VERSION"
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Final version: $VERSION"
          
      - name: Debug environment variables
        run: |
          echo "MAVEN_USERNAME is set: ${{ secrets.MAVEN_USERNAME != '' }}"
          echo "MAVEN_PASSWORD is set: ${{ secrets.MAVEN_PASSWORD != '' }}"
          echo "Checking environment variables..."
          env | grep -E "ORG_GRADLE_PROJECT_|GITHUB_" | sort

      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            -PmavenCentralUsername=${{ secrets.MAVEN_USERNAME }}
            -PmavenCentralPassword=${{ secrets.MAVEN_PASSWORD }}
            -PsigningInMemoryKeyId=${{ secrets.MAVEN_GPG_KEY_ID }}
            -PsigningInMemoryPassword=${{ secrets.MAVEN_GPG_PASSPHRASE }}
            publishToSonatype closeAndReleaseSonatypeStagingRepository
          
      - name: Auto-merge PR on successful deployment
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            if (pr) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'merge'
              });
              console.log(`PR #${pr.number} has been automatically merged after successful deployment`);
            }